server:
  port: 8080
#
## DataBase
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo_springBoot

    username: root
    password: uhbujhbq
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    hibernate:
        ddl-auto: update

